version: "3.9"
services:
  server:
    build: .
    volumes:
       - .:/code
    ports:
      - "5000:5000"
  frontend:
    build: client
    ports:
      - "8080:8080"
  mongo:
    image: "mongo:latest"
